---
ct_amount: 5
tt_amount: 5
number_of_rounds: 10
starting_money: 500
player_health: 100
defuse_time: 2500
time_to_plant: 2500
bomb_dmg: 200
round_winner_money: 600
round_loser_money: 200
buy_time: 20000
bomb_time: 90000
after_round_time: 10000
money_per_kill: 600
tiles_per_movement: 5
game_rate: 30
knife:
  min_dmg: 40
  max_dmg: 80
  range: 30
  angle: 0.39269908169872414 # pi / 8
glock:
  max_ammo: 20
  starting_reserve_ammo: 40
  min_dmg: 30
  max_dmg: 50
  gun_price: 200
ak:
  max_ammo: 30
  starting_reserve_ammo: 60
  min_dmg: 20
  max_dmg: 45
  gun_price: 600
  bullets_per_burst: 3
  shoot_cooldown: 2500