name: Pre-commit checks

on:
  pull_request:
  push:
    branches: [main, CI]

jobs:
  pre-commit:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install cppcheck
        run: sudo apt-get --yes install cppcheck

      - name: Install cpplint
        run: python -m pip install cpplint
 
      - name: Install pre-commit
        run: pip install pre-commit

      - name: Install pre-commit hooks
        run: pre-commit install  

      - name: Run pre-commit
        run: pre-commit run --all-files
